### ISSUE TITLE
[어드민] 로그인 페이지 기능 테스트 정의

### ISSUE THREAD

**Issue by djkeh** [djkeh/fastcampus-project-board-admin#17]
로그인 기능을 구현하기 위해 테스트가 필요한지 검토하고, 어드민 회원 기능과 카카오 OAuth 인증을 준비한다.

## Todo

* [x] 로그인 설정 및 테스트 검토
* [x] 어드민 회원 기능 검토
* [x] 카카오 OAuth 인증 준비 및 테스트 검토
