### ISSUE TITLE
[어드민] 데이터베이스 접근 로직 테스트 정의

### ISSUE THREAD

**Issue by djkeh** [djkeh/fastcampus-project-board-admin#6]
어드민 프로젝트가 데이터베이스를 사용할 수 있게끔 환경을 구성하고 테스트를 정의한다.

## TODO

* [x] db 만들기
* [x] 계정 권한 주기
* [x] IDE 접근 환경 꾸미기
* [ ] repository 코드 작성
* [ ] 관련 테스트 작성
